import type { PayrollTriageException } from "@/types/models";

export const MOCK_PAYROLL_EXCEPTIONS: PayrollTriageException[] = [
  {
    id: "exc_001",
    runId: "run_2025_02",
    category: "zk_proof",
    severity: "blocking",
    status: "open",
    title: "Zero-Knowledge Circuit Verification Mismatch",
    description: "The zk-SNARK proof public inputs hash does not match the merkle root of the batch payroll commitments.",
    source: "circuit_verifier",
    employeeCount: 4,
    affectedEmployees: [
      { id: "emp_001", name: "Alice Mensah", department: "Engineering", salaryCommitmentHash: "0xabc1...f456 (Redacted)" },
      { id: "emp_002", name: "Kwame Asante", department: "Product", salaryCommitmentHash: "0xdef7...h012 (Redacted)" },
    ],
    suggestedAction: "Re-generate ZK proof with updated membership tree and re-submit circuit witnesses.",
    nextStepUrl: "/payroll",
    createdAt: "2025-02-28T09:15:00Z",
    redactedProofDigest: "zkp_digest_7f8a...331b",
  },
  {
    id: "exc_002",
    runId: "run_2025_02",
    category: "treasury",
    severity: "blocking",
    status: "open",
    title: "Insufficient Treasury Balance for USDC Disbursement",
    description: "Treasury vault balance is 12,500 USDC below the required reservation threshold for scheduled batch execution.",
    source: "treasury_guard",
    employeeCount: 12,
    affectedEmployees: [
      { id: "emp_003", name: "Amara Diallo", department: "Finance", salaryCommitmentHash: "0xghi3...j678 (Redacted)" },
      { id: "emp_004", name: "Kofi Boateng", department: "Engineering", salaryCommitmentHash: "0xmno9...p234 (Redacted)" },
    ],
    suggestedAction: "Deposit minimum 12,500 USDC to treasury contract or adjust allocation schedule.",
    nextStepUrl: "/treasury",
    createdAt: "2025-02-28T10:30:00Z",
  },
  {
    id: "exc_003",
    runId: "run_2025_02",
    category: "employee_data",
    severity: "warning",
    status: "investigating",
    title: "Unverified Stellar Trustline for Asset Payout",
    description: "Recipient wallet has not established trustline for custom EURC token prior to execution window.",
    source: "wallet_router",
    employeeCount: 2,
    affectedEmployees: [
      { id: "emp_005", name: "Fatima Al-Mansoor", department: "Operations", salaryCommitmentHash: "0xpqr5...s789 (Redacted)" },
    ],
    suggestedAction: "Notify employee to accept EURC trustline or fall back to XLM native payout.",
    nextStepUrl: "/employees",
    createdAt: "2025-02-28T11:00:00Z",
  },
  {
    id: "exc_004",
    runId: "run_2025_01",
    category: "compliance",
    severity: "warning",
    status: "open",
    title: "Auditor Attestation Key Near Expiration",
    description: "The periodic auditor view key expires in 3 days. On-chain compliance verification may fail if not rotated.",
    source: "compliance_check",
    employeeCount: 0,
    suggestedAction: "Issue new auditor view key rotation transaction via compliance dashboard.",
    nextStepUrl: "/compliance",
    createdAt: "2025-02-27T14:20:00Z",
  },
  {
    id: "exc_005",
    runId: "run_2025_01",
    category: "network",
    severity: "info",
    status: "resolved",
    title: "Horizon RPC Congestion Detected",
    description: "Temporary fee spike on Stellar Testnet caused 2 transaction submissions to retry with exponential backoff.",
    source: "oracle_bridge",
    employeeCount: 8,
    suggestedAction: "No action required — automated retry mechanism successfully completed the submission.",
    createdAt: "2025-02-25T08:00:00Z",
    resolvedAt: "2025-02-25T08:02:15Z",
  },
];
