"use client";

import { useState, useEffect } from "react";
import {
  Key,
  Plus,
  Shield,
  AlertTriangle,
  Clock,
  CheckCircle,
  XCircle,
  Copy,
  Eye,
  EyeOff,
  Download,
  Loader2,
} from "lucide-react";
import { toast } from "sonner";
import { useViewKeyStore } from "@/stores/viewKeys";
import { useAuditRequestStore } from "@/stores/auditRequests";
import { useAuditActivityStore } from "@/stores/auditActivity";
import { MOCK_VIEW_KEYS, MOCK_AUDIT_REQUESTS, MOCK_TRANSACTIONS } from "@/lib/api/mockData";
import { HelpButton } from "@/components/ui/HelpDrawer";
import AuditActivityFeed from "./AuditActivityFeed";
import type { ViewKey } from "@/types";
import AuditExportRequest from "./AuditExportRequest";
import ComplianceEvidenceBundleView from "./ComplianceEvidenceBundleView";
import AuditReadyTimeline from "@/components/features/payroll/AuditReadyTimeline";
import type { AuditAccessRequest } from "@/types/models";

function generateKeyId(): string {
  const chars = "abcdefghijklmnopqrstuvwxyz0123456789";
  let result = "vk_";
  for (let i = 0; i < 12; i++) {
    result += chars[Math.floor(Math.random() * chars.length)];
  }
  return result;
}

function ComplianceManager() {
  const { viewKeys, addViewKey, revokeViewKey, setViewKeys } =
    useViewKeyStore();
  const [activeTab, setActiveTab] = useState<"access" | "exports" | "bundles" | "timeline">("access");
  const {
    requests,
    setRequests,
    approveRequest,
    rejectRequest,
    revokeRequestByViewKey,
    markExportReady,
    addRequest,
  } = useAuditRequestStore();
  const { addActivity } = useAuditActivityStore();
  
  const [showForm, setShowForm] = useState(false);
  const [revealedKeys, setRevealedKeys] = useState<Set<string>>(new Set());
  const [form, setForm] = useState({
    auditorName: "",
    auditorOrg: "",
    scope: "read-only" as "read-only" | "full-audit",
  });
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [preparingId, setPreparingId] = useState<string | null>(null);

  useEffect(() => {
    if (viewKeys.length === 0) setViewKeys(MOCK_VIEW_KEYS);
    if (requests.length === 0) setRequests(MOCK_AUDIT_REQUESTS);
  }, [viewKeys.length, requests.length, setViewKeys, setRequests]);


  const handleApproveRequest = (request: AuditAccessRequest) => {
    const keyId = generateKeyId();
    const newKey: ViewKey = {
      id: `vk_${Date.now()}`,
      keyId,
      auditorName: request.requesterName,
      auditorOrg: request.requesterOrg,
      scope: request.scope,
      grantedBy: "Current Admin",
      createdAt: new Date().toISOString(),
      expiresAt: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
      isActive: true,
    };
    addViewKey(newKey);
    approveRequest(request.id, newKey.id);
    addActivity({
      id: `aud_act_${Date.now()}`,
      action: "request_approved",
      actor: "Current Admin",
      actorOrg: "ZK Payroll Inc.",
      targetName: request.requesterName,
      targetOrg: request.requesterOrg,
      scope: request.scope,
      timestamp: new Date().toISOString(),
      summary: `Audit access request from ${request.requesterName} (${request.requesterOrg}) approved. View key issued.`,
    });
    toast.success("Request Approved", {
      description: `View key generated for ${request.requesterName}.`,
    });
  };

  const handleRejectRequest = (id: string) => {
    rejectRequest(id);
    const req = requests.find((r) => r.id === id);
    if (req) {
      addActivity({
        id: `aud_act_${Date.now()}`,
        action: "request_rejected",
        actor: "Current Admin",
        actorOrg: "ZK Payroll Inc.",
        targetName: req.requesterName,
        targetOrg: req.requesterOrg,
        scope: req.scope,
        timestamp: new Date().toISOString(),
        summary: `Audit access request from ${req.requesterName} (${req.requesterOrg}) rejected.`,
      });
    }
    toast.success("Request Rejected", {
      description: "The audit access request has been rejected.",
    });
  };

  const handleGenerate = () => {
    const keyId = generateKeyId();
    const newKey: ViewKey = {
      id: `vk_${Date.now()}`,
      keyId,
      auditorName: form.auditorName,
      auditorOrg: form.auditorOrg,
      scope: form.scope,
      grantedBy: "Current Admin",
      createdAt: new Date().toISOString(),
      expiresAt: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
      isActive: true,
    };
    addViewKey(newKey);

    // Create corresponding request to keep request tracking unified
    const reqId = `req_${Date.now()}`;
    const newRequest: AuditAccessRequest = {
      id: reqId,
      requesterName: form.auditorName,
      requesterOrg: form.auditorOrg,
      requesterEmail: `${form.auditorName.toLowerCase().replace(/\s+/g, ".")}@${form.auditorOrg.toLowerCase().replace(/\s+/g, "")}.com`,
      scope: form.scope,
      rationale: "Manually generated by administrator.",
      status: "approved",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      viewKeyId: newKey.id,
    };
    addRequest(newRequest);

    addActivity({
      id: `aud_act_${Date.now()}`,
      action: "key_granted",
      actor: "Current Admin",
      actorOrg: "ZK Payroll Inc.",
      targetName: form.auditorName,
      targetOrg: form.auditorOrg,
      scope: form.scope,
      timestamp: new Date().toISOString(),
      summary: `View key generated manually for ${form.auditorName} (${form.auditorOrg}).`,
    });

    setForm({ auditorName: "", auditorOrg: "", scope: "read-only" });
    setShowForm(false);
    toast.success("View key generated", {
      description: "Auditor access has been granted.",
    });
  };

  const handleRevoke = (id: string) => {
    revokeViewKey(id);
    revokeRequestByViewKey(id);
    const key = viewKeys.find((k) => k.id === id);
    if (key) {
      addActivity({
        id: `aud_act_${Date.now()}`,
        action: "key_revoked",
        actor: "Current Admin",
        actorOrg: "ZK Payroll Inc.",
        targetName: key.auditorName,
        targetOrg: key.auditorOrg,
        scope: key.scope,
        timestamp: new Date().toISOString(),
        summary: `View key for ${key.auditorName} (${key.auditorOrg}) revoked. Access immediately invalidated.`,
      });
    }
    toast.success("View key revoked", {
      description: "Auditor access has been immediately revoked.",
    });
  };

  const toggleReveal = (id: string) => {
    setRevealedKeys((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  };

  const copyKeyId = async (keyId: string, id: string) => {
    await navigator.clipboard.writeText(keyId);
    setCopiedId(id);
    toast.success("Copied to clipboard", {
      description: "Key ID copied to clipboard.",
    });
    setTimeout(() => setCopiedId(null), 2000);
  };

  const handlePrepareExport = (id: string) => {
    setPreparingId(id);
    setTimeout(() => {
      markExportReady(id);
      setPreparingId(null);
      
      const req = requests.find((r) => r.id === id);
      if (req) {
        addActivity({
          id: `aud_act_${Date.now()}`,
          action: "export_prepared",
          actor: "Current Admin",
          actorOrg: "ZK Payroll Inc.",
          targetName: req.requesterName,
          targetOrg: req.requesterOrg,
          scope: req.scope,
          timestamp: new Date().toISOString(),
          summary: `Audit export compiled and ready for ${req.requesterName} (${req.requesterOrg}).`,
        });
        toast.success("Audit Export Prepared", {
          description: `The audit export for ${req.requesterName} is now ready to download.`,
        });
      }
    }, 1200);
  };

  const handleDownloadExport = (req: AuditAccessRequest) => {
    const toCsvRow = (values: Array<string | number | null | undefined>) => {
      return values
        .map((value) => {
          const text = value == null ? "" : String(value);
          return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
        })
        .join(",");
    };

    const downloadCsv = (filename: string, rows: Array<Array<string | number | null | undefined>>) => {
      const csv = rows.map(toCsvRow).join("\n");
      const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
      const url = URL.createObjectURL(blob);
      const anchor = document.createElement("a");
      anchor.href = url;
      anchor.download = filename;
      anchor.click();
      URL.revokeObjectURL(url);
    };

    if (req.scope === "full-audit") {
      downloadCsv(`audit-export-${req.requesterOrg.toLowerCase()}-full.csv`, [
        ["Transaction ID", "Date", "Status", "Total Amount", "Employee Count", "Department Breakdown", "Verification Proof Hash"],
        ...MOCK_TRANSACTIONS.map((tx) => [
          tx.id,
          new Date(tx.createdAt).toISOString().slice(0, 10),
          tx.status,
          tx.totalAmount,
          tx.employeeCount,
          "Engineering: 40%, Marketing: 25%, Operations: 20%, Sales: 15%",
          tx.txHash ?? "0x7f8d8b8e8f8...zkProof",
        ]),
      ]);
    } else {
      downloadCsv(`audit-export-${req.requesterOrg.toLowerCase()}-summary.csv`, [
        ["Transaction ID", "Date", "Status", "Total Amount", "Employee Count"],
        ...MOCK_TRANSACTIONS.map((tx) => [
          tx.id,
          new Date(tx.createdAt).toISOString().slice(0, 10),
          tx.status,
          tx.totalAmount,
          tx.employeeCount,
        ]),
      ]);
    }

    addActivity({
      id: `aud_act_${Date.now()}`,
      action: "export_downloaded",
      actor: "Current Admin",
      actorOrg: "ZK Payroll Inc.",
      targetName: req.requesterName,
      targetOrg: req.requesterOrg,
      scope: req.scope,
      timestamp: new Date().toISOString(),
      summary: `Audit export downloaded by ${req.requesterName} (${req.requesterOrg}).`,
    });

    toast.success("Audit Export Downloaded", {
      description: `CSV file for ${req.requesterName} has been downloaded.`,
    });
  };

  const isKeyExpired = (key: ViewKey) => {
    return new Date(key.expiresAt).getTime() < Date.now();
  };

  const getRequestStatus = (req: AuditAccessRequest) => {
    if (req.status === "pending" || req.status === "rejected") {
      return req.status;
    }
    const key = viewKeys.find(
      (k) => k.id === req.viewKeyId || k.keyId === req.viewKeyId
    );
    if (!key) return req.status;
    if (key.revokedAt || !key.isActive) {
      return "revoked";
    }
    if (isKeyExpired(key)) {
      return "expired";
    }
    return req.status; // approved or export_ready
  };

  const activeKeys = viewKeys.filter((k) => k.isActive && !isKeyExpired(k));
  const inactiveKeys = viewKeys.filter((k) => !k.isActive || isKeyExpired(k));
  const pendingRequests = requests.filter((r) => r.status === "pending");

  return (
    <section aria-labelledby="compliance-heading" className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2
            id="compliance-heading"
            className="text-lg font-semibold text-gray-900"
          >
            Auditor Access Management
          </h2>
          <p className="text-sm text-gray-600 mt-1">
            Manage and monitor compliance-related activities. Selective disclosure
            and scope-limited exports ensure data privacy.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <HelpButton page="compliance" label="Help" />
        </div>
      </div>

      {/* Tab Switcher */}
      <div className="flex border-b border-gray-200">
        <button
          type="button"
          onClick={() => setActiveTab("bundles")}
          className={`px-6 py-3 text-sm font-medium transition-colors relative ${
            activeTab === "bundles"
              ? "text-indigo-600 font-semibold"
              : "text-gray-500 hover:text-gray-700"
          }`}
        >
          Evidence Bundles
          {activeTab === "bundles" && (
            <div className="absolute bottom-0 left-0 right-0 h-0.5 bg-indigo-600 animate-in fade-in slide-in-from-bottom-1" />
          )}
        </button>
        <button
          type="button"
          onClick={() => setActiveTab("access")}
          className={`px-6 py-3 text-sm font-medium transition-colors relative ${
            activeTab === "access"
              ? "text-indigo-600 font-semibold"
              : "text-gray-500 hover:text-gray-700"
          }`}
        >
          Access Management
          {activeTab === "access" && (
            <div className="absolute bottom-0 left-0 right-0 h-0.5 bg-indigo-600 animate-in fade-in slide-in-from-bottom-1" />
          )}
        </button>
        <button
          type="button"
          onClick={() => setActiveTab("exports")}
          className={`px-6 py-3 text-sm font-medium transition-colors relative ${
            activeTab === "exports"
              ? "text-indigo-600 font-semibold"
              : "text-gray-500 hover:text-gray-700"
          }`}
        >
          Audit Exports
          {activeTab === "exports" && (
            <div className="absolute bottom-0 left-0 right-0 h-0.5 bg-indigo-600 animate-in fade-in slide-in-from-bottom-1" />
          )}
        </button>
        <button
          type="button"
          onClick={() => setActiveTab("timeline")}
          className={`px-6 py-3 text-sm font-medium transition-colors relative ${
            activeTab === "timeline"
              ? "text-indigo-600 font-semibold"
              : "text-gray-500 hover:text-gray-700"
          }`}
        >
          Audit Timeline
          {activeTab === "timeline" && (
            <div className="absolute bottom-0 left-0 right-0 h-0.5 bg-indigo-600 animate-in fade-in slide-in-from-bottom-1" />
          )}
        </button>
      </div>

      {activeTab === "access" ? (
        <div className="space-y-6">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-semibold text-gray-900 uppercase tracking-wider">
              Auditor View Keys
            </h3>
            <button
              type="button"
              onClick={() => setShowForm(!showForm)}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium bg-indigo-600 text-white hover:bg-indigo-700 transition-colors"
            >
              <Plus className="w-3.5 h-3.5" />
              Generate Key
            </button>
          </div>

          <div className="bg-amber-50 border border-amber-200 rounded-lg p-4">
            <div className="flex items-start gap-3">
              <Shield className="w-5 h-5 text-amber-600 mt-0.5 shrink-0" />
              <div>
                <h4 className="text-sm font-medium text-amber-800">
                  Privacy Notice
                </h4>
                <p className="text-xs text-amber-700 mt-1">
                  View keys allow auditors to decrypt specific payroll data without
                  exposing full employee records. Read-only keys permit viewing
                  transaction summaries. Full-audit keys additionally reveal
                  departmental breakdowns. Revoking a key immediately invalidates
                  access.
                </p>
              </div>
            </div>
          </div>

          {showForm && (
            <div
              role="form"
              aria-label="Generate new view key"
              className="bg-white rounded-lg border p-6 space-y-4 shadow-sm"
            >
              <h3 className="text-sm font-semibold text-gray-900">
                New Auditor View Key
              </h3>
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                <div>
                  <label
                    htmlFor="auditor-name"
                    className="block text-xs font-medium text-gray-600 mb-1"
                  >
                    Auditor Name
                  </label>
                  <input
                    id="auditor-name"
                    type="text"
                    value={form.auditorName}
                    onChange={(e) =>
                      setForm((f) => ({ ...f, auditorName: e.target.value }))
                    }
                    placeholder="e.g. Sarah Chen"
                    className="w-full rounded-md border border-gray-300 px-3 py-1.5 text-sm focus:ring-2 focus:ring-indigo-500 focus:outline-none"
                  />
                </div>
                <div>
                  <label
                    htmlFor="auditor-org"
                    className="block text-xs font-medium text-gray-600 mb-1"
                  >
                    Organization
                  </label>
                  <input
                    id="auditor-org"
                    type="text"
                    value={form.auditorOrg}
                    onChange={(e) =>
                      setForm((f) => ({ ...f, auditorOrg: e.target.value }))
                    }
                    placeholder="e.g. Deloitte"
                    className="w-full rounded-md border border-gray-300 px-3 py-1.5 text-sm focus:ring-2 focus:ring-indigo-500 focus:outline-none"
                  />
                </div>
                <div>
                  <label
                    htmlFor="auditor-scope"
                    className="block text-xs font-medium text-gray-600 mb-1"
                  >
                    Access Scope
                  </label>
                  <select
                    id="auditor-scope"
                    value={form.scope}
                    onChange={(e) =>
                      setForm((f) => ({
                        ...f,
                        scope: e.target.value as "read-only" | "full-audit",
                      }))
                    }
                    className="w-full rounded-md border border-gray-300 bg-white px-3 py-1.5 text-sm focus:ring-2 focus:ring-indigo-500 focus:outline-none"
                  >
                    <option value="read-only">Read-only</option>
                    <option value="full-audit">Full Audit</option>
                  </select>
                </div>
              </div>
              <div className="flex gap-2">
                <button
                  type="button"
                  onClick={handleGenerate}
                  disabled={!form.auditorName || !form.auditorOrg}
                  className="px-4 py-2 rounded-md text-sm font-medium bg-indigo-600 text-white hover:bg-indigo-700 disabled:opacity-50 transition-colors"
                >
                  Generate
                </button>
                <button
                  type="button"
                  onClick={() => setShowForm(false)}
                  className="px-4 py-2 rounded-md text-sm font-medium bg-gray-100 text-gray-700 hover:bg-gray-200 transition-colors"
                >
                  Cancel
                </button>
              </div>
            </div>
          )}

          {pendingRequests.length > 0 && (
            <div>
              <h3 className="text-sm font-semibold text-gray-900 mb-3 flex items-center gap-2">
                <Clock className="w-4 h-4 text-amber-600" />
                Pending Requests ({pendingRequests.length})
              </h3>
              <div className="bg-white rounded-lg border divide-y">
                {pendingRequests.map((req) => (
                  <div key={req.id} className="px-6 py-4 flex flex-col md:flex-row md:items-center justify-between gap-4">
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2">
                        <span className="font-medium text-sm text-gray-900">{req.requesterName}</span>
                        <span className="text-sm text-gray-500">({req.requesterOrg})</span>
                        <span
                          className={`inline-flex items-center gap-1 px-2 py-0.5 text-xs font-medium rounded-full ${
                            req.scope === "full-audit"
                              ? "bg-purple-100 text-purple-800"
                              : "bg-blue-100 text-blue-800"
                          }`}
                        >
                          {req.scope === "full-audit" ? "Full Audit" : "Read-only"}
                        </span>
                      </div>
                      <p className="text-sm text-gray-600 mt-1">{req.rationale}</p>
                      <div className="flex items-center gap-3 mt-1">
                        <span className="text-xs text-gray-500">
                          Requested {new Date(req.createdAt).toLocaleDateString()}
                        </span>
                        <span className="text-xs text-gray-500">
                          {req.requesterEmail}
                        </span>
                      </div>
                    </div>
                    <div className="flex items-center gap-2 shrink-0">
                      <button
                        type="button"
                        onClick={() => handleApproveRequest(req)}
                        className="px-3 py-1.5 rounded-md text-xs font-medium bg-green-50 text-green-700 hover:bg-green-100 border border-green-200 transition-colors flex items-center gap-1"
                      >
                        <CheckCircle className="w-3 h-3" />
                        Approve
                      </button>
                      <button
                        type="button"
                        onClick={() => handleRejectRequest(req.id)}
                        className="px-3 py-1.5 rounded-md text-xs font-medium bg-red-50 text-red-700 hover:bg-red-100 border border-red-200 transition-colors flex items-center gap-1"
                      >
                        <XCircle className="w-3 h-3" />
                        Reject
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {activeKeys.length > 0 && (
            <div>
              <h4 className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-3 flex items-center gap-2">
                <CheckCircle className="w-3.5 h-3.5 text-green-600" />
                Active Keys ({activeKeys.length})
              </h4>
              <div className="bg-white rounded-lg border divide-y">
                {activeKeys.map((key) => (
                  <ViewKeyRow
                    key={key.id}
                    viewKey={key}
                    isRevealed={revealedKeys.has(key.id)}
                    isCopied={copiedId === key.id}
                    onToggleReveal={() => toggleReveal(key.id)}
                    onCopy={() => copyKeyId(key.keyId, key.id)}
                    onRevoke={() => handleRevoke(key.id)}
                  />
                ))}
              </div>
            </div>
          )}

          {inactiveKeys.length > 0 && (
            <div className="pt-6">
              <h4 className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-3 flex items-center gap-2">
                <XCircle className="w-3.5 h-3.5 text-gray-400" />
                Revoked Keys ({inactiveKeys.length})
              </h4>
              <div className="bg-white rounded-lg border divide-y opacity-75">
                {inactiveKeys.map((key) => (
                  <ViewKeyRow
                    key={key.id}
                    viewKey={key}
                    isRevealed={revealedKeys.has(key.id)}
                    isCopied={copiedId === key.id}
                    onToggleReveal={() => toggleReveal(key.id)}
                    onCopy={() => copyKeyId(key.keyId, key.id)}
                    onRevoke={() => {}}
                  />
                ))}
              </div>
            </div>
          )}

          {/* Access Request Tracking Section */}
          <div className="pt-6 border-t border-gray-200">
            <h4 className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-3 flex items-center gap-2">
              <Clock className="w-3.5 h-3.5 text-gray-400" />
              Access Request Tracking
            </h4>
            {requests.length === 0 ? (
              <div className="bg-white rounded-lg border p-6 text-center text-sm text-gray-500">
                No access requests on record.
              </div>
            ) : (
              <div className="bg-white rounded-lg border overflow-hidden shadow-sm">
                <div className="overflow-x-auto">
                  <table className="min-w-full divide-y divide-gray-200">
                    <thead className="bg-gray-50">
                      <tr>
                        <th scope="col" className="px-6 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">
                          Requester
                        </th>
                        <th scope="col" className="px-6 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">
                          Scope
                        </th>
                        <th scope="col" className="px-6 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">
                          Status
                        </th>
                        <th scope="col" className="px-6 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">
                          Requested On
                        </th>
                        <th scope="col" className="px-6 py-3 text-right text-xs font-semibold text-gray-500 uppercase tracking-wider">
                          Actions
                        </th>
                      </tr>
                    </thead>
                    <tbody className="bg-white divide-y divide-gray-200">
                      {requests.map((req) => {
                        const currentStatus = getRequestStatus(req);
                        return (
                          <tr key={req.id} className="hover:bg-gray-50/50 transition-colors">
                            <td className="px-6 py-4 whitespace-nowrap">
                              <div className="flex flex-col">
                                <span className="text-sm font-semibold text-gray-900">
                                  {req.requesterName}
                                </span>
                                <span className="text-xs text-gray-500">
                                  {req.requesterOrg} &middot; {req.requesterEmail}
                                </span>
                              </div>
                            </td>
                            <td className="px-6 py-4 whitespace-nowrap">
                              <span
                                className={`inline-flex items-center gap-1 px-2 py-0.5 text-xs font-medium rounded-full ${
                                  req.scope === "full-audit"
                                    ? "bg-purple-100 text-purple-800"
                                    : "bg-blue-100 text-blue-800"
                                }`}
                              >
                                {req.scope === "full-audit" ? "Full Audit" : "Read-only"}
                              </span>
                            </td>
                            <td className="px-6 py-4 whitespace-nowrap">
                              <StatusBadge status={currentStatus} />
                            </td>
                            <td className="px-6 py-4 whitespace-nowrap text-xs text-gray-500">
                              {new Date(req.createdAt).toLocaleDateString()}
                            </td>
                            <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                              <RequestActions
                                request={req}
                                status={currentStatus}
                                onPrepareExport={handlePrepareExport}
                                onDownloadExport={handleDownloadExport}
                                preparingId={preparingId}
                              />
                            </td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                </div>
              </div>
            )}
          </div>

          <AuditActivityFeed />
        </div>
      ) : activeTab === "exports" ? (
        <AuditExportRequest />
      ) : activeTab === "timeline" ? (
        <AuditReadyTimeline />
      ) : (
        <ComplianceEvidenceBundleView />
      )}
    </section>
  );
}

function ViewKeyRow({
  viewKey,
  isRevealed,
  isCopied,
  onToggleReveal,
  onCopy,
  onRevoke,
}: {
  viewKey: ViewKey;
  isRevealed: boolean;
  isCopied: boolean;
  onToggleReveal: () => void;
  onCopy: () => void;
  onRevoke: () => void;
}) {
  const isExpired =
    (!viewKey.isActive && !viewKey.revokedAt) ||
    new Date(viewKey.expiresAt).getTime() < Date.now();
  const displayKey = isRevealed
    ? viewKey.keyId
    : viewKey.keyId.slice(0, 6) + "****";

  return (
    <div className="px-6 py-4 flex items-center justify-between gap-4">
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2">
          <Key className="w-4 h-4 text-gray-400 shrink-0" />
          <span className="font-mono text-sm text-gray-900">{displayKey}</span>
          <button
            type="button"
            onClick={onToggleReveal}
            className="p-0.5 text-gray-400 hover:text-gray-600 transition-colors"
            aria-label={isRevealed ? "Hide key" : "Reveal key"}
          >
            {isRevealed ? (
              <EyeOff className="w-3.5 h-3.5" />
            ) : (
              <Eye className="w-3.5 h-3.5" />
            )}
          </button>
          <button
            type="button"
            onClick={onCopy}
            className="p-0.5 text-gray-400 hover:text-gray-600 transition-colors"
            aria-label="Copy key ID"
          >
            <Copy className="w-3.5 h-3.5" />
            {isCopied && (
              <span className="text-xs text-green-600 ml-1">Copied</span>
            )}
          </button>
        </div>
        <p className="text-sm text-gray-600 mt-1">
          {viewKey.auditorName} &middot; {viewKey.auditorOrg}
        </p>
        <div className="flex items-center gap-3 mt-1">
          <span
            className={`inline-flex items-center gap-1 px-2 py-0.5 text-xs font-medium rounded-full ${
              viewKey.isActive
                ? viewKey.scope === "full-audit"
                  ? "bg-purple-100 text-purple-800"
                  : "bg-blue-100 text-blue-800"
                : "bg-gray-100 text-gray-600"
            }`}
          >
            {viewKey.scope === "full-audit" ? "Full Audit" : "Read-only"}
          </span>
          <span className="text-xs text-gray-500 flex items-center gap-1">
            <Clock className="w-3 h-3" />
            Expires {new Date(viewKey.expiresAt).toLocaleDateString()}
          </span>
          {viewKey.revokedAt && (
            <span className="text-xs text-red-500">
              Revoked {new Date(viewKey.revokedAt).toLocaleDateString()}
            </span>
          )}
        </div>
      </div>
      {viewKey.isActive && (
        <button
          type="button"
          onClick={onRevoke}
          className="shrink-0 px-3 py-1.5 rounded-md text-xs font-medium bg-red-50 text-red-700 hover:bg-red-100 border border-red-200 transition-colors flex items-center gap-1"
        >
          <AlertTriangle className="w-3 h-3" />
          Revoke
        </button>
      )}
    </div>
  );
}

function StatusBadge({ status }: { status: string }) {
  const configs: Record<string, { bg: string; label: string }> = {
    pending: { bg: "bg-amber-100 text-amber-800 border border-amber-200", label: "Pending Review" },
    approved: { bg: "bg-blue-100 text-blue-800 border border-blue-200", label: "Approved" },
    rejected: { bg: "bg-red-100 text-red-800 border border-red-200", label: "Rejected" },
    expired: { bg: "bg-gray-100 text-gray-800 border border-gray-200", label: "Expired" },
    revoked: { bg: "bg-red-100 text-red-800 border border-red-200", label: "Revoked" },
    export_ready: { bg: "bg-green-100 text-green-800 border border-green-200", label: "Export Ready" },
  };

  const config = configs[status] || { bg: "bg-gray-100 text-gray-800 border border-gray-200", label: status };

  return (
    <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${config.bg}`}>
      {config.label}
    </span>
  );
}

function RequestActions({
  request,
  status,
  onPrepareExport,
  onDownloadExport,
  preparingId,
}: {
  request: AuditAccessRequest;
  status: string;
  onPrepareExport: (id: string) => void;
  onDownloadExport: (req: AuditAccessRequest) => void;
  preparingId: string | null;
}) {
  if (status === "approved") {
    const isPreparing = preparingId === request.id;
    return (
      <button
        type="button"
        disabled={isPreparing}
        onClick={() => onPrepareExport(request.id)}
        className="inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-md text-xs font-semibold bg-indigo-50 text-indigo-700 hover:bg-indigo-100 border border-indigo-200 transition-colors disabled:opacity-50"
      >
        {isPreparing ? (
          <>
            <Loader2 className="w-3 h-3 animate-spin" />
            Preparing...
          </>
        ) : (
          "Prepare Export"
        )}
      </button>
    );
  }

  if (status === "export_ready") {
    return (
      <button
        type="button"
        onClick={() => onDownloadExport(request)}
        className="inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-md text-xs font-semibold bg-green-50 text-green-700 hover:bg-green-100 border border-green-200 transition-colors"
      >
        <Download className="w-3 h-3" />
        Download Export
      </button>
    );
  }

  return <span className="text-xs text-gray-400">—</span>;
}

export default ComplianceManager;
